#!/usr/bin/env bash
# This script pings an IP address 5 times or shows usage if no IP is given

if [ $# -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"
